name: Update AdGuard Home Rules

on:
  schedule:
    - cron: "0 0 * * *"  # 每天午夜自动运行
  push:
    branches:
      - main  # 监听 main 分支的推送事件

jobs:
  update-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run script to update AdGuard Home rules
      run: bash generate_formatted_list.sh

    - name: Commit and push updated rules
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add adguard_home_rules.txt
        git commit -m "Update AdGuard Home rules"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
