name: Update AdGuard Home Rules

on:
  push:
    branches:
      - main  # 触发工作流的分支
  workflow_dispatch:  # 支持手动触发工作流

jobs:
  update:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境运行

    steps:
      # 步骤 1: 检出当前仓库的代码
      - name: Checkout repository
        uses: actions/checkout@v3  # 自动使用 GITHUB_TOKEN 进行身份验证

      # 步骤 2: 运行脚本生成规则文件
      - name: Run the script to generate the rules
        run: |
          chmod +x generate_formatted_list.sh  # 确保脚本具有执行权限
          ./generate_formatted_list.sh  # 执行脚本生成规则文件

      # 步骤 3: 提交并推送更改到仓库
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"  # 设置提交者名称
          git config --global user.email "github-actions[bot]@users.noreply.github.com"  # 设置提交者邮箱
          git add adguard_home_rules.txt  # 将生成的规则文件添加到 git 暂存区
          git commit -m "Update AdGuard Home rules"  # 提交更改
          git push origin HEAD:main  # 将更改推送到 main 分支
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 自动提供的 token 进行推送
