name: Update and Generate Formatted List

on:
  schedule:
    - cron: "0 2 * * *" # 每天凌晨 2 点运行
  workflow_dispatch: # 手动触发工作流
  push:
    branches:
      - main

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Bash shell
      run: sudo apt-get update && sudo apt-get install -y curl

    - name: Run the script
      run: |
        chmod +x generate_formatted_list.sh
        ./generate_formatted_list.sh

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add formatted_list.txt
        git commit -m "Update formatted list"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
