name: Update AdGuard Home Rules

on:
  push:
    branches:
      - main  # 触发工作流的分支
  workflow_dispatch:  # 支持手动触发工作流

jobs:
  update:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境运行

    steps:
      # 检出当前仓库的代码
      - name: Checkout repository
        uses: actions/checkout@v3  # 通过 GITHUB_TOKEN 自动进行身份验证

      # 运行脚本生成规则
      - name: Run the script to generate the rules
        run: |
          chmod +x generate_formatted_list.sh
          ./generate_formatted_list.sh

      # 提交并推送更改
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add adguard_home_rules.txt
          git commit -m "Update AdGuard Home rules"
          git push origin HEAD:main  # 推送到当前仓库的 main 分支
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的 GITHUB_TOKEN 进行身份验证
